### PR TITLE
GetSystemCapability_detailed_info.md

### PR DESCRIPTION
**Pull request by OlesiaV**
use case for Requirement #1

### CODE REVIEW

**Comment by yang1070** [comment]
> 1. App requests RC capabilities of available modules with corresponding control items

No parameters in the GetSystemCapability request to indicate "available modules". SDL just give all available in RemoteControlCapabilities.

> 4. SDL checks if requested modules are allowed by Policies.

This is old requirement. Not needed any more for GetSystemCapability request with REMOTE_COTNROL system capability type .

**Comment by yang1070** [comment]
> Alternative flow 1

> 6.a.1 One of the requested modules is not available on HMI

> 6.a.2 SDL transfers to mobile application capabilities of available on HMI module and responds with WARNINGS "%moduleType% is not available" for anavailable module 

no longer apply

**Comment by OlesiaV** [comment]
I created this PR before GetInteriorVehicleCapabilities were changed to GetSystemData. As of now keep this branch open just as a spare with opportunity to change it later, since GetSystemCapability is out of our scope

**Comment by yang1070** [comment]
looks good to me

**Pull request merged**
