### PR TITLE
Feature/fuel range

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
Add functional requirements (TRS, UCs) and diagrams for RPCs
GetVehicleData
SubscribeVehicleData
UnSubscribeVehicleData
OnVehicleData

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@robinmk, please review

**Comment by KhrystynaDubovyk** [comment]
@robinmk, kindly reminder

**Comment by robinmk** [comment]
@KhrystynaDubovyk , Review comments added.

**Comment by KhrystynaDubovyk** [comment]
@robinmk, please see updated diagrams (with `fuelRange`, `engineOilLife` parameters)
Please, confirm merging PR to master branch.

**Pull request merged**
