### PR TITLE
Create button_press_emulation.md

### PR DESCRIPTION
**Pull request by OlesiaV**
Use case that describes SDL behavior in case application requested button press even emulation

### CODE REVIEW

**Comment by yang1070** [comment]
> Exceptions:
> 1.6 Requested module is busy with processing request from another application -> SDL responds IN_USE and doesn't process this request

 Requested module may not be busy with processing request, but locked to another application.

additional one
1.7 Requested module is busy with processing request from the same application -> SDL responds IN_USE and doesn't process this request

**Comment by OlesiaV** [comment]
1.7 added

1.6 - why not if app_1 was in control of the module and sent the request for processing, user activated app_2, app_2 wants to get in control of the module but it is still busy with processing of request from app_1

**Comment by yang1070** [comment]
The original 1.6 is a valid use case. What I said 'Requested module may not be busy with processing request, but locked to another application." is actually 1.5 : "Requested module is already in control by another app and control cannot be transferred to requested app -> SDL responds IN_USE and doesn't process the request"

**Comment by yang1070** [comment]
It seems
>Pre-conditions:
>e. "MODULE_1" is not in control by another app

 conflicts with 1.5 and 1.6

But in general, it looks good to me

**Comment by OlesiaV** [comment]
Agree, removed 1.5 and 1.6 - the behavior is described in resource allocation

**Comment by yang1070** [comment]
looks good

**Pull request merged**
