### PR TITLE
Feature/SDL passenger mode

### PR DESCRIPTION
**Pull request by KhrystynaDubovyk**
**Is related to**
https://github.com/smartdevicelink/sdl_core/issues/2134

This PR is **[ready]** for review.

### Summary
Add API folder; add OnDriverDistraction folder with TRS, UC, accessories

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by LuxoftAKutsan — APPROVED** [review]

**Review by LuxoftAKutsan — APPROVED** [review]

**Comment by LuxoftAKutsan** [comment]
@KhrystynaDubovyk where o you use the image OnDriverDistraction_lockScreenDismissalEnabled.png
? I would put it in to the TRS

**Comment by KhrystynaDubovyk** [comment]
@LuxoftAKutsan, thank you.
fixed https://github.com/smartdevicelink/sdl_requirements/commit/8e31101ac7d730a133c9fd67488ce2fb5f64f442

**Comment by KhrystynaDubovyk** [comment]
@HSavynetska, @ValeriiMalkov, @IGapchuk any other suggestions?

**Review by IGapchuk — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by yang1070 — APPROVED** [review]
Ford has reviewed and approved this PR.

**Pull request merged**
