### PR TITLE
GetInteriorVehicleData_TRS.md

### PR DESCRIPTION
**Pull request by OlesiaV**

### CODE REVIEW

**Comment by yang1070** [comment]
case 1 (added "isSubscribed: <current_subscription_status>" to the related app) conflicts with case 7 and 11 (without "isSubscribed")

**Comment by OlesiaV** [comment]
Case 1 - any except error, will update. Thank you

**Comment by yang1070** [comment]
what the happens for the cases:

-case (1) app already subscribed to CLIMATE, but send GetInteriorVehicleData_request with subscribe=true again? Does SDL forward subscribe=true to HMI or just remove it and keep the subscription.

-case (2) app does not subscribe to CLIMATE, but send GetInteriorVehicleData_request with subscribe=false? Does SDL maintain the state as unsubsribed and cut off the subscribe=false in request to HMI or forward it to HMI and wait for HMI's decision?

**Comment by yang1070** [comment]
[rc_subsribe.xlsx](https://github.com/smartdevicelink/sdl_requirements/files/1170232/rc_subsribe.xlsx)

**Comment by yang1070** [comment]
rc_subsribe

**Comment by OlesiaV** [comment]
Case 1 - SDL forwards subscribe parameter but the subscription status remains unchanged
Case 2 - by default the app is unsubscribed from notifications and if app wasn't subscribed and sends subscribed:false, SDL forwards the parameter but keeps the status of the app unchanged - unsubscribed

**Comment by yang1070** [comment]
[rc_subsribe.xlsx](https://github.com/smartdevicelink/sdl_requirements/files/1170256/rc_subsribe.xlsx)
rc_subsribe

**Comment by yang1070** [comment]
I suggest in those two cases, SDL does not forward subscribe parameter to HMI, otherwise, HMI may response with issubscribe = true/faslse/not present, then SDL shall handle them with more cases in line 10 to 17

**Comment by yang1070** [comment]
Also my understanding of subscription of RC module data is : on SDL side it is per app and per module. on HMI side it is per module only. Thus on HMI side, as long as there is at least one app subscribed to a module, HMI shall send data change notifications to SDL. HMI does not care which app subscribed to the data, it cares whether there is any app subscribed to the data. SDL shall disseminate a notification to multiple apps who subscribed to the same module data.

**Comment by OlesiaV** [comment]
Added 12, 13 with ignoring "subscribed" parameter in request to HMI in case the subscription status doesn't change.

Your understanding is correct - it is SDL's responsibility to track subscribed/unsubscribed apps to modules and forward module status change notifications appropriately

**Comment by OlesiaV** [comment]
>when an app un-subscribe an existing subscribed module, SDL forwards subscribe=false to HMI. BUT SDL shall un-subscribe the app no mater the HMI response is_subscribed=false or true. (case 8 remain, but case 9 change)
Disagree SDL should not ignore HMI's response and if HMI responded isSubscribed:true, SDL shouldn't unsubscribe the app (btw in HMI_API request to HMI has appID, so maybe there is some logic of storing subscriptions for apps on HMI (maybe only the number of apps). 
What if that was the only application subscribed and requests to unsubscribe, HMI didn't unsubscribe (sent isSubscribed:true), SDL will ignore HMI's response, and HMI will keep sending notifications even though there are no apps subscribed on SDL side? SDL should take into consideration HMI responses.

**Comment by yang1070** [comment]
> What if that was the only application subscribed and requests to unsubscribe, HMI didn't unsubscribe (sent isSubscribed:true), 

In this case, there is a bug in HMI side and shall be fixed. SDL shall ignore the notifications from HMI if there is no app subscribed.

**Comment by OlesiaV** [comment]
Still disagree - we have the opposite case when SDL considers HMI's response and doesn't subscribe app in case app requested subscribe:true and HMI responded isSubscribed:false. The logic has to be consistent in both ways.

**Comment by yang1070** [comment]
OK. I understand your point about "The logic has to be consistent in both ways."
But I want to understand why (1) HMI will give isSubscribed:false response to subscribe:true request and (2) HMI will give isSubscribed:true response to subscribe:false request. I think both cases are not normal use case, they are exceptions and indicate some errors in the HMI side. Those errors shall be fixed before deliverer. In first case, SDL can do nothing about it as HMI failed to subscribe to the moduletype data change and will not send notifications to SDL. Therefore, SDL must accept the result from HMI and give it back to mobile.

> Your understanding is correct - it is SDL's responsibility to track subscribed/unsubscribed apps to modules and forward module status change notifications appropriately

In the second case, SDL can make a decision on its own (as app want to unsubscribe and SDL maintains the subscription status of each app/module inside of SDL) and ignore the isSubscribed in  HMI response and cut off the extra notifications when necessary.

**Comment by OlesiaV** [comment]
> I think both cases are not normal use case, they are exceptions and indicate some errors in the HMI side. Those errors shall be fixed before deliverer.

1. Both of these cases were present in use cases ( [Unsubscribe from RC module status change notification](https://github.com/smartdevicelink/sdl_requirements/blob/master/detailed_docs/unsubscribe_from_module_status_change_notification.md), [Subscription on module status change notification](https://github.com/smartdevicelink/sdl_requirements/blob/master/detailed_docs/subscription_on_module_status_change_notification.md) alternative flow 1) that you approved and the code was developed appropriatelly
2. We develop SDL code not HMI but we need to correctly handle any responses from HMI. And if HMI did not unsubscribe from notifications for whatever reason - SDL shouldn't. The same as in case when any error happened on HMI side (case 11) 
3. When I noted that it is SDL responsibility to track subscribed/unsubscribed apps I meant that SDL receives OnInteriorVehicleData notification without appID from HMI, so SDL has to figure out to which app to forward such notification

**Comment by yang1070** [comment]
agree to the keep the current use cases and implementation.
Just want to say when designing the functionality, we need to consider an app developer's perspective to see the whole system, if an app want to subscribe or unsubscribe, the expectation is success, and if it is not success, there shall be a good reason.

**Comment by OlesiaV** [comment]
Fails on HMI side is a geed reason.

Please advise if I can merge this PR?

**Comment by OlesiaV** [comment]
@yang1070 if you finished with review please approve this PR

**Comment by OlesiaV** [comment]
@yang1070 any updates?

**Comment by yang1070** [comment]
looks good, please merge

**Pull request merged**
