### PR TITLE
Policies_for_RC_TRS.md

### PR DESCRIPTION
**Pull request by OlesiaV**
TRS with requirements about Policy support of RC functionality

### CODE REVIEW

**Comment by yang1070** [comment]
in case 9,
> allow app's remote-control RPCs that contain any of "moduleType" parameters

does this 'any of "moduleType" parameters' must be listed in the default section?

what's the difference of  "moduleType"  array in the default section and the appid subsection?
In the appid subsection, non-existence of array means disallow everything, empty array means allow everything (define in default section?), non-empty array means a white list of moduleType.
In the default section what does the 3 cases (not exist, exist but empty, non empty) mean?

**Comment by OlesiaV** [comment]
When application is running on consented device and there was no PTU, application has "default" policies assigned. After PTU application receives pre_consented groups and app's specific policies. ModuleType is included in either "default" or app's specifice policies means that no matter if there was PTU or not, application will have access to moduleTypes.
Abot moduleTypes:
1. if there is no moduleType at all either in "default" or app's specific policies it means that application doesn't have access to any of the RC modules. All requests with "moduleType" parameters will be failed with result code "DISALLOWED"
2. if there is moduleType and it is empty array - it means that all moduleTypes are allowed for this application, so if application will send request with moduleType CLIMATE or RADIO or both - such moduleTypes are allowed and in case all other parameters are valid and RPC itself is allowed by policies - such request will be processed.
3. if it is assigned a specific moduleType in policies it means if for example moduleType in policies is CLIMATE and application sends the request with moduleType CLIMATE, in case if other params are valid and RPC is allowed then such RPC will be processed, if app will send RPC for moduleType RADIO - such rpc won't be processed and result code will be DISALLOWED

**Comment by yang1070** [comment]
Thank you for clarifying this. 
As summary, If there is no app specific policy (usually before PTU), SDL use settings in default section. If there is app specific policy (usually after PTU), SDL use app specific settings in appID section (in this case default settings is ignored). 

non-existence of moduleType array means disallow every moduleType, empty moduleType array means allow every moduleType, non-empty moduleType  array means a white-list of moduleTypes.

**Comment by OlesiaV** [comment]
Correct

**Comment by OlesiaV** [comment]
@yang1070 any updates? Can this PR be merged?

**Comment by yang1070** [comment]
please merge

**Pull request merged**
