### PR TITLE
SetInteriorVehicleData.md

### PR DESCRIPTION
**Pull request by OlesiaV**
Use case describes system behavior for SetInteriorVehicleData RPC

### CODE REVIEW

**Comment by yang1070** [comment]
3.1 Request is disallowed by policies -> SDL returns USER_DISALLOWED and doesn't transfer the request to HMI. 
USER_DISALLOWED --> DISALLOWED

**Comment by yang1070** [comment]
5.1 Requested moduleType_X is unavailable on HMI -> SDL returns DISALLOWED and doesn't transfer the request to HMI. Does unavailable mean that the remoteControlCapabilities does not contain moduleType_X ?
UNSUPPORTED_RESOURCE might be a better result code.

**Comment by yang1070** [comment]
>> 6. SDL checks if signed in request moduleType_X is controlled by another application
Need an additional check that the moduleType_X is not busy. No current request pending finish to the same moduleType_X

**Comment by yang1070** [comment]
> 7.2 Application requested to set available control settings with read only and settable control items -> SDL cuts off read_only control items and transfers only settable control items to HMI

Similar to above, assume moduleType_X and if there are parameters than moduleType_X supports, the additional parameters are cut off

**Comment by OlesiaV** [comment]
3.1 It is tandard behavior in case RPC is not included in functional grouping of assigned policies - SDL returns USER_DISALLOWED
5.1 Agree, will update
6. This check is described in resource allocation use case
7.2 That's exactly the meaning of it

**Comment by yang1070** [comment]
7.2 What I mean if xxxModuleControlData has control items a,b,c,d,e, but the request has control item x,y,z. Do you cut off x,y,z or do you return INVALID_DATA?

**Comment by OlesiaV** [comment]
7.2 means that module has a,b,c,d settable items and x,y,z, read_only items, if app sends SetInteriorVehicleData with x,y,z only - the response will be INVALID_DATA, SDL won't request to set data for read_only parameters
The case case that you described - mobile app sent only fake items it will be INVALID_DATA
In case app sent a,b,c,d,x,y,z where x,y,z are fake - items that don't exist at all or they are related to another module then SDL will cut them off and transfer only a,b,c,d

**Comment by yang1070** [comment]
looks good to me

**Pull request merged**
