### PR TITLE
SetInteriorVehicleData_TRS

### PR DESCRIPTION
**Pull request by OlesiaV**
TRS for SetInteriorVehicleData

### CODE REVIEW

**Comment by yang1070** [comment]
case 6 
> application sent SetInteriorVehicleData with one or more settable parameters in "*ControlData" struct, for the appropriate muduleType
and HMI responds with "resultCode: READ_ONLY"

I don't understand why HMI respond READ_ONLY.

**Comment by yang1070** [comment]
is radioEnable is read-only paramter?

**Comment by OlesiaV** [comment]
case 6 - it can be some fail on HMI side, but SDL needs to handle any responses from HMI

> is radioEnable is read-only paramter?

According to your proposal it is unclear because in Type signed "Get/Set/Notification" and in comments "read only, all other radio control items need radio enabled to work" 

| RC Module | Control Item | Value Range |Type | Comments |
| ------------ | ------------ |------------ | ------------ | ------------ |
| Radio | Radio Enabled | true,false  | Get/Set/Notification| read only, all other radio control items need radio enabled to work|

**Comment by OlesiaV** [comment]
@yang1070 can you please advise what should SDL check first when receives SetInteriorVehicleData from application:

a. parameters of request - if request has settable parameters

b. if requested module is in "free" state or control under requested module can be taken

My assumption that SDL should check the parameters of request first and then check if requested resource can be allocated

**Comment by yang1070** [comment]
Agree that SDL should check the parameters of request first and then check if requested resource can be allocated

**Comment by yang1070** [comment]
Yes, there is inconsistency in the proposal. I heard that in the existing implementation it is read only. But we have a use case that allows an app to switch audio source from app streaming via Bluetooth to physical radio tuner. To me that (switch to radio tuner, or turn on radio tuner) sounds exactly like to set radioEnable=ture. That caused my confusion.

**Comment by OlesiaV** [comment]
@yang1070 I put the table with control items in Non-functional requirements and deleted "read-only" from description of "Radio Enabled", so it must be considered as settable parameter. Please review and confirm that types for other control items remain unchanged

**Comment by OlesiaV** [comment]
@yang1070 if you finished with review please approve this PR

**Comment by OlesiaV** [comment]
@yang1070  any updates?

**Comment by yang1070** [comment]
please merge.

**Pull request merged**
