### PR TITLE
SDL shall not put RC applications to HMI level NONE when user disables RC in HMI

### PR DESCRIPTION
**Pull request by LitvinenkoIra**
**Fixes https://github.com/smartdevicelink/sdl_core/issues/2377**
https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0181-keep-rc-app-hmi-level-when-disable-rc.md

This PR is **[ready]** for review.

### Testing Plan

test set: https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/fix/rc_disabling/test_sets/rc_CLIMATE_RADIO.txt
PR for scripts: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/1979

### Summary
Fix behavior in case when RC functionality is disabled from HMI

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Comment by yang1070** [comment]
Please update OnRemoteControlSettings_disablingRC.png, in which it says `app1 cannot be activated while RC functionality is disabled on HMI`, which shall be removed.
When RC disabled, we still allow activate RC applications.

**Comment by LitvinenkoIra** [comment]
@yang1070 Fixed 6aefc8cceb726f9c756c5b5feb902dc66d911286

**Comment by LitvinenkoIra** [comment]
@yang1070 Updated f994b74

**Review by yang1070 — APPROVED** [review]
The change looks good to me

**Pull request merged**
