### PR TITLE
rc_enabling_disabling.md

### PR DESCRIPTION
**Pull request by OlesiaV**
@yang1070 , please review this PR

### CODE REVIEW

**Comment by yang1070** [comment]
looks good to me

**Comment by yang1070** [comment]
> SDL unsubscribes all applications from RC_modules on HMI

Does it mean SDL send GetInteriorVehicleData with subscribe=false for all existing RC apps?

**Comment by OlesiaV** [comment]
No, SDL unsubscribes apps internally and doesn't send anything to apps. It means that in case RC feature disabled but for some reason will still send OnInteriorVehicleData with changed module settings, SDL won't transfer this notification to any RC app

**Comment by OlesiaV** [comment]
@yang1070 , please advise if this use case can be merged

**Comment by OlesiaV** [comment]
@yang1070 if you finished with review please approve this PR

**Comment by OlesiaV** [comment]
@yang1070 any updates?

**Comment by yang1070** [comment]
@OlesiaV in use case 1, please add SDL release all allocated modules.
Looks good to me.

**Pull request merged**
