### PR TITLE
SendLocation

### PR DESCRIPTION
**Pull request by OlesiaV**
PR with SendLocation use case and TRS

### CODE REVIEW

**Comment by KhrystynaDubovyk** [comment]
@robinmk, please review.

**Comment by OlesiaV** [comment]
@robinmk I committed a few changes in Use case and TRS (corrected validation and diagram), please review

**Comment by robinmk** [comment]
Sorry, I seem to have missed this. Will review this today.

**Comment by OlesiaV** [comment]
@robinmk 
These requirements were added according to the following line in [proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0004-sendlocation-updates.md):

"Check allowance of SendLocation by "deliveryMode" value in Policy component"

**Comment by robinmk** [comment]
@OlesiaV ,
Thank you for pointing this out. I think we should be good to merge then.
A quick question: If the delivery mode param is missing from the PTU (not empty), then the SendLocation request is treated as PROMPT right?

**Comment by OlesiaV** [comment]
@robinmk 
In case the delivery mode is missing then SDL is not transferring this parameter to HMI, but it is expected from HMI that it will use the default value of delivery mode which is PROMPT

**Comment by robinmk** [comment]
Ok, thanks

**Pull request merged**
