### PR TITLE
Create Policy_Support_of_basic_RC_functionality.md

### PR DESCRIPTION
**Pull request by OlesiaV**
Use cases that describe Policy and number of connected devices check

### CODE REVIEW

**Comment by yang1070** [comment]
> Use Case 2: Number of connected devices with RC-applications

I would like not list this use case here. Reason as following
- Currently, for regular apps, SDL allow apps from multiple devices to register. This use case will introduce a special logic that deviated from that implementation. 
- In the future, we would like to allow RC apps from multiple devices to register.

**Comment by OlesiaV** [comment]
This use case and user story is for basic policy support that we deliver now. When the Policies will be expanded the user story with this use case will be closed as implemented and new user story will be created.
I specifically didn't sign the number of devices in user story since the number can be changed and as a result - the use case will be changed too, but as of now we need a use case that describes current system behavior.
Please also note that this use case allows application from other device to register if they are not remote control that doesn't conflict with current non-RC system behavior

**Comment by yang1070** [comment]
I would rather not add this policy device number check, so that we don't need add it now and remove later

**Comment by OlesiaV** [comment]
OK, I will remove second use case

**Comment by yang1070** [comment]
looks goo to me

**Pull request merged**
