### PR TITLE
GetInteriorVehicleDataConsent_TRS

### PR DESCRIPTION
**Pull request by OlesiaV**
GetInteriorVehicleDataConsent TRS for resource allocation

### CODE REVIEW

**Comment by yang1070** [comment]
> and RC application requested access to remote control module that is already allocated to another RC application

need to note the hmi level
and RC application (in HMI level FULL) requested access to remote control module that is already allocated to another RC application


There is an extra message GetInteriorDataConsent(allowed: ture) from HMI to SDL in the figure in opt block, between two sub-opts

**Comment by OlesiaV** [comment]
It's not an extra message, if you read the diagram, you may see the sequence:
SDL requested consent
opt1 - HMI responds with TIMED_OUT - RPC is not processed
opt2 - HMI responds allowed:true - RPC is processed
opt3 - HMI responds with invalid params - SDL returns GENERIC_ERROR
ALT - HMI responds allowed:false - SDL returns REJECTED

**Comment by yang1070** [comment]
The sequence of messages ( GetInteriorDataConsent(allowed: ture) is in between TIMED_OUT block and invalid params block , and no indication of opt2 block)  is confusing to me. Suggest to move the message after block of "SDL returns GENERIC_ERROR". So that this message and later successful messages can be together.

**Comment by OlesiaV** [comment]
Updated

**Comment by yang1070** [comment]
Looks good

**Pull request merged**
