### PR TITLE
OnRemoteControlSettings_TRS

### PR DESCRIPTION
**Pull request by OlesiaV**
OnRemoteControlSettings notification for Resource allocation and RC feature enabling/disabling

### CODE REVIEW

**Comment by yang1070** [comment]
I would like to say the list of points in very cases is not a message sequence, it is like some preconditions. When SDL receives OnRemoteControlSettings, it save the value of allowed and accessMode.

if there is a switch of allow from true to false, or from false to true, there are additional steps need by SDL. But if there is a change of accessMode, SDL just remember it for later use.

Later, when SDL receives a RC request, it checks those states (allowed, and accessMode) and acts correspondingly.

**Comment by yang1070** [comment]
Additionally, as both 'allowed' and 'accessMode' are optional parameters of OnRemoteControlSettings, in theory, HMI can have only 'accessMode' in a OnRemoteControlSettings notification.

**Comment by yang1070** [comment]
I would like re-write case 1
>In case
>SDL received OnRemoteControlSettings notification from HMI with allowed:true
and "accessMode" = "AUTO_ALLOW" or without "accessMode" parameter at all
and RC_module on HMI is alreay in control by RC-application

to 
In case
SDL has RCSettings: allowed=true (SDL saved the state of RCSettings according to OnRemoteControlSettings)
SDL has RCSettings:accessMode=auto_allow

**Comment by OlesiaV** [comment]
That parameters are optional in OnRemoteControlsettings is clear from HMI_API, the purpose of TRS is to clarify behavior described in USE CASE, no need to clarify details of implementation and no need to rephrase case 1 - in any case SDL obtains RC settings via notification from HMI and that is described, also there is not such parameter in HMI_API as RCSettings and your option looks confusing. If we describe SDL behavior based on received notification it is better to operate with parameters signed in API.
And yes those points in every case is like precondition.
The structure of every requirement is precondition and then SDL behavior for such case.

**Comment by OlesiaV** [comment]
@yang1070 the purpose of review is to make sure that nothing is missed (all cases of possible behavior are described). Please advise if there are no conflicts in behavior. If everything is fine - please approve this PR

**Comment by yang1070** [comment]
I agree use cases should not have details of implementation.  But I think OnRemoteControlsettings and resource allocation shall be separated.  Processing OnRemoteControlsettings is simple. The use cases shall include (1) consider allowed parameter only (Regarding enable/disable RC), (2) consider accessMode parameter only (3) consider combinations of the two parameters, and (4) consider the default value. 

values of accessMode and allowed are only two factors of resource allocation, other factors like resource status (free, busy, in use), if in use who has it, and applications' HMI level are all inputs to resource allocation.

I would like the TRS can cover all the possible cases, but that is no guarantee nothing is missing even after my review. What I can do is only to make sure the listed use cases are correct, there is no conflicts, and anything I can think of during the reading of the cases.

Regarding the missing use cases, what about the case of
(1) SDL receives an OnRemoteControlSettings that only has accessMode, without allowed:true, depending on the value of accessMode, this is really 3 cases.
(2) SDL receives multiple  OnRemoteControlSettings with conflict accessMode values, only the last value is saved and used later.

**Comment by OlesiaV** [comment]
@yang1070 please do not confuse documents.

We have user story for resource allocation and use case for that user story
And we have user story for disabling RC functionality and separate use case for this user story

TRS - collects all requirements for the RPC. In case the behavior will be changed or new parameters added -  TRS will be expanded with new requirements BUT if the feature purpose will remain the same - user story won't be changed.

Regarding cases - in TRS there are requirements for 3 different access modes and it doesn't matter if HMI provided "allowed" parameter or not when sent the access mode parameter, if RC feature is enabled, SDL will act according to described in p. 1-5

What do you mean by  "OnRemoteControlSettings with conflict accessMode values", SDL is using the last one received. if it was AUTO_ALLOW and then HMI sent AUTO_DENY, SDL will use auto deny. There is no point to describe this in requirements as it already clear from the existing ones. 

If the last OnRemoteControlSettings was allowed:false and then HMI sends OnRemoteControlSettings with accessMode parameter and without allowed parameter, SDL will discard such notification since RC functionality is off and it cannot have any accessMode

I specifically didn't sign in requirements that SDL saves something internally - this is the detail of implementation, the same as detail of implementation if SDL compares the received value with newly received or just rewrites - this is not the purpose of requirement. Purpose of requirement is to clarify what SDL should do when it received the notification with specified in requirement parameters.

Please advise if everything is clear in SDL behavior described in TRS? If the described in TRS behavior is what was expected in proposal?

if both answers are "yes", please approve this PR

**Comment by yang1070** [comment]
The statement here
>Regarding cases - in TRS there are requirements for 3 different access modes and it doesn't matter if HMI provided "allowed" parameter or not when sent the access mode parameter, if RC feature is enabled, SDL will act according to described in p. 1-5

conflicts the precondition in cases 1-5, where allowed:true shall be in OnRemoteControlSettings 
>SDL received OnRemoteControlSettings notification from HMI with allowed:true

**Comment by OlesiaV** [comment]
@yang1070 
The thing is that according to current logic SDL takes into consideration access mode if RC functionality is enabled. Let's say HMI provided this parameter before or it is set by default, so HMI can send any access mode and SDL will act according to requirements 1-5. I specified the allowed: true to emphasize that these requirements are applicable only when RC functionality is enabled. When RC functionality is disabled then it doesn't matter what access mode is provided by HMI since app won't have access to any RC modules in any case.
Please clarify what is the conflict?

**Comment by OlesiaV** [comment]
I will update p. 1 and p. 3 specifying that AUTO_ALLOW is default parameter in case HMI didn't provide access mode

**Comment by yang1070** [comment]
my point is RC allowed:true is also default. 
if on start up, HMI sends OnRemoteControlSettings with accessMode=any but without allowed:true. SDL shall allow RC. 
this is different from p1-p5, which requires allow:true be explicitly included in the OnRemoteControlSettings. 
Please update p8 to include this scenario.
Otherwise, looks good to me.

**Pull request merged**
